# Generated by Django 5.2.9 on 2026-05-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_size_product_pr_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color_filter',
            old_name='name',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cf',
            new_name='color_filter',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pr_size',
            new_name='size_filter',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='name',
            new_name='s_name',
        ),
    ]
