# Generated by Django 5.2.14 on 2026-05-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_name_color_filter_c_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color_filter',
            new_name='Color',
        ),
    ]
