# Generated by Django 5.2.14 on 2026-05-27 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_color_filter_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color',
            new_name='Color_filter',
        ),
    ]
