# Generated by Django 5.2.14 on 2026-06-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='User',
        ),
    ]
