# Generated by Django 5.2.14 on 2026-06-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_register_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Human',
        ),
    ]
