# Generated by Django 5.2.14 on 2026-06-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
