# Generated by Django 5.2.14 on 2026-06-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_human_email_alter_human_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='password',
            field=models.CharField(max_length=5000),
        ),
    ]
